apiVersion: v1
kind: Service
metadata:
  name: postgresql-db-service
  labels: 
    app: postgresql-db
spec:
  type: NodePort
  selector:
    app: postgresql-db
  ports: 
    - port: 5432
      targetPort: 5432
